### ISSUE TITLE
Support Unicode / Emoji in Team Names

### ISSUE THREAD

**Issue by mpsijm** [icpctools/icpctools#402]
Suggestion: better support for Unicode characters or emoji in team names in the Resolver (and probably in other tools as well).

Take for example these two team names from [BAPC 2020](https://2020.bapc.eu/scoreboard):
<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/9739541/117210660-48cfba80-adf8-11eb-85e8-c7279da45e09.png)

The default font (Helvetica) which is shipped with ICPCtools does not support many of these characters:
![image](https://user-images.githubusercontent.com/9739541/117210763-69981000-adf8-11eb-85da-82c164fe8e80.png)

This already improves when switching to a different font, I took DejuVu Sans as an example:
![image](https://user-images.githubusercontent.com/9739541/117210873-8e8c8300-adf8-11eb-99c5-b9819458e434.png)

However, as far as I know, there does not exist a font that supports both "regular" letters and symbols and (color) emoji at the same time. For example, the [twemoji](https://github.com/eosrei/twemoji-color-font) font _only_ supports emoji but no letters:
![image](https://user-images.githubusercontent.com/9739541/117211437-4457d180-adf9-11eb-8635-25623ca0f366.png)
</details>

I see two challenges here:
1. Use two fonts at once (one main font and a fallback font). This can be solved by:
   - Merging multiple fonts together to have it support both "regular" symbols (main) and emoji (fallback). I've tried [merging fonts](https://superuser.com/a/1594984) with [FontForge](https://fontforge.org/), but without success.
   - [generating an `AttributedString`](https://stackoverflow.com/a/9482676) and printing that. This would require changes at all locations in the code where a team name is printed, though.
2. In the last screenshot, the emoji are rendered in black-and-white, but it would be better if they are in color. This [seems to be possible](https://stackoverflow.com/a/43950434), but I have not tested this yet. 

I just wanted to ventilate my thoughts before trying to code this up and create a PR. Any comments or hints are appreciated :slightly_smiling_face:

**Comment by deboer-tim** [comment]
Thanks for the bug report. I've been aware of this for years but haven't found a solution nor copied the bug report from the bugzilla system we used to use. I last looked at this a couple years ago (and several times before that) and couldn't find any reliable way to do it. I still have a changeset with OpenSansEmoji.ttf as a fallback font that only partially worked... I was trying to check each character in the string and switch fonts when necessary.

The StackOverflow link looks hopeful, and although colour would be really cool I think this would be worth doing even in black and white. I agree we'll probably have to implement a custom g.drawString() and route all team name output to it (and maybe organization or group in the future), so once that is done we can always improve the implementation.

The hardest part is proving we can draw any string containing emojis, even if that's in one presentation or just in a standalone app. If you have any luck with that I can easily hook it into all the places that would be required. If you can't figure it out or don't have time, I can take a look at this again in a week or two.

**Comment by mpsijm** [comment]
I've done some more experimenting, and I got some things to work in https://github.com/mpsijm/icpctools/commit/16edacb361f7eeb29910f37107cec50c4501ee4c :smile: 

<details>
<summary>Preview:</summary>

![image](https://user-images.githubusercontent.com/9739541/119222181-51f8a100-baf3-11eb-8c7e-dbfcc836ff09.png)
</details>

To get both Migos and DuckGiraffe to render correctly, I had to use three fonts, combined into an `AttributedString` with help from the Stack Overflow link I mentioned before. I replaced Helvetica with Roboto for now, since the old Helvetica font seems to support only the most basic glyphs. I've implemented a way to override these fallback fonts as well, to make it easier for users of the Resolver to select the correct fonts to render all team names correctly. Hopefully this satisfies your "proving we can draw any string containing emojis" requirement :slightly_smiling_face: 

I didn't get colored emoji to work, but after doing some further research, it looks like that would [require manually rendering the emoji images](https://stackoverflow.com/questions/57972693/how-to-show-color-emoji#comment102356850_57972693). So, at this point, these black-and-white emoji should be "good enough" :stuck_out_tongue:

Similarly, "combined" emoji (with the [zero-width joiner](https://en.wikipedia.org/wiki/Zero-width_joiner)) don't seem to work. BAPC 2020 had a team with the name "🤔👨‍💻👨‍💻👨‍💻😕" (where the ["male programmer" emoji](https://emojipedia.org/man-technologist/) is a combination of the "man" and "laptop" emoji), and it's currently rendered as follows:
<details>
<summary>"combined" emoji are split up</summary>

![image](https://user-images.githubusercontent.com/9739541/119222259-b1ef4780-baf3-11eb-9d1b-8342dba0a15b.png)
</details>

But again, that's probably "good enough" for now. :joy:

**Comment by deboer-tim** [comment]
Thank you! Holiday weekend and compressed week here, but I will try to test and get this in shortly.

**Comment by deboer-tim** [comment]
I'm _really_ sorry this took so long, but the support is finally in. I initially started with the approach in your fork, but after investigating a bit more and looking at options for supporting the zero-width spacer, I ended up switching to using pngs for the emojis. This is oddly slightly smaller than the font file and feels like an odd way to do this, but gives full support for colour and combination emojis like 👨‍💻.

I've tried to catch all presentations where team names are shown and switch to this, but it's possible I've missed one, and other strings (e.g. group, org names) haven't been changed. If someone ever requests it I'd be happy to use this technique everywhere.

I'm really happy we were finally able to get emoji support in, and would love any feedback. Thank you for taking the time to contribute and make this happen!

**Comment by mpsijm** [comment]
Super cool that emoji work now! :smile: :tada: 

I see that you reverted the fallback fonts in favor of PNG rendering, which I totally agree is the way to go when you want to render all possible combinations of emoji, with the zero-width joiner. However, it seems like the default font (Helvetica) is still missing some Unicode characters that are _not_ emoji. In the `event-feed.json` from BAPC 2020 that I used to test, the emoji render perfectly, but the Migos team is still missing some characters (see screenshot).

<details>
<summary>Screenshot:</summary>

![Untitled](https://user-images.githubusercontent.com/9739541/134049159-5e593e15-ff2c-4ffd-a2df-74a8ad01b096.png)
![Untitled](https://user-images.githubusercontent.com/9739541/134049278-ac2d8df3-d959-4629-a323-5dbfbb2cb24f.png)
</details>

The current setup with the `TextHelper` is not very well fit for fallback fonts, unfortunately. I did find a font that does contain most the required characters for this team, namely [FreeSans](https://www.fontspace.com/freesans-font-f13276), but it's still missing the [☼](https://www.compart.com/en/unicode/U+263C) character:

<details>
<summary>Screenshot:</summary>

![Untitled](https://user-images.githubusercontent.com/9739541/134051375-c4f6ba4c-0029-4478-8b4c-43b1be412514.png)
</details>

I've tried out some different fonts as well, but some that do have the [☼](https://www.compart.com/en/unicode/U+263C) character will then not have all other characters for the Migos team, or interfere with the emoji rendering. In fact, it seems that it is impossible to have a font that supports _all_ possible code points ([source](https://stackoverflow.com/a/34734338)), which implies that a system with "fallback fonts" or "font families" is unavoidable, but I can live with this for now.
However, for the interference with emoji, I have devised a fix at [`mpsijm:unicode`](https://github.com/icpctools/icpctools/compare/main...mpsijm:unicode). The fix is to give priority to the PNGs when rendering text, instead of only trying to render a PNG when the font does not support a certain character. This branch also includes some other commits with small fixes. I can open a PR, I just wanted to check with you if this sounds like a good idea :slightly_smiling_face:

**Comment by deboer-tim** [comment]
Helvetica is the ICPC font, so although I'm open to easier ways to override it I'd prefer to leave it as the default.

I'm also good with giving preference to the emojis whenever there is a match. (The zero-width-joiner check I put in there was ... temporary)

I think a second/fallback font could be used to improve the missing characters, but I think the fact FreeSans doesn't have the ☼ character either is probably an indication that no font (or likely even 2 or 3) is likely to have every character. Instead of using a fallback font I'm wondering if it's better to just use pngs for non-emoji as well - i.e. find or create a bunch of other images for characters that aren't strictly emoji but also aren't common.

People have already started leaving for World Finals (there is a *lot* going on this year) so just giving you a heads-up that we'll be 'offline' and under pressure not to push changes for a couple weeks.

**Comment by mpsijm** [comment]
Thanks for your feedback, Tim! I removed the FreeSans font again, and opened PR #456 :slightly_smiling_face: Good luck at the World Finals, I understand that this gives you less time to look at my changes. I'll supply the DAPC organization with a locally built version in case we run into emoji trouble :stuck_out_tongue: 

The solution of using PNGs for non-emoji sounds like a good idea :smile: Now that I think of it, is there any reason to use PNGs over SVGs, by the way?

**Comment by deboer-tim** [comment]
Sorry, I totally messed this up by putting up a PR last night that incorporated most of your changes from yesterday, but also heavily modified the class to allow clients to add regular images and spacers, etc. The purpose of my other changes was:
- To support the team intro presentation better, which needs a logo and spacer beside the team name.
- To scale better when text needs to fit within a given width (team intro + both scoreboards). It now uses a transform to scale image/text/emojis to fit exactly in a given width instead of trying multiple font scalings but nothing else.

I added a quick change to pick up your font override improvement and I _think_ that pulls in everything critical from your PR. (?) Please let me know if there's anything I missed (and sorry I will close your PR since it won't apply and the changes are already there), but once again *thank you* for continuing to contribute because these changes wouldn't have happened without you.

The main reason I didn't use SVGs to start was that I couldn't find them that night :) , but I have now: https://github.com/twitter/twemoji/tree/gh-pages/v/13.1.0. The files are roughy 2x the size of the 72px pngs, but would give unlimited scaling. The Java SVG library currently used doesn't handle all SVGs but I highly doubt it would have a problem with these, so I agree it will make sense to switch at some point.

FWIW, I also looked for a backup font that would cover more of the non-emoji characters, or another PNG/SVG set that we could use to cover these, and so far I haven't found anything great to use for either.

**Comment by mpsijm** [comment]
Ah, oh well, I should've at least checked the list of open PRs to see you beat me to it :joy: Yes, all of my changes are in there, thanks a lot! :smile: 

RE SVGs: Nice! Would be cool to see those used at some point indeed, but it's not really a priority because most strings are displayed with font sizes smaller than 72 anyway :stuck_out_tongue: 

RE fallback fonts: that's too bad, bottomline is that fonts are a pain :joy: But Unicode support in ICPCtools is already a lot better now :smile: :tada:
