### ISSUE TITLE
Only show the university logo once on team presentation

### ISSUE THREAD

**Issue by niemela** [icpctools/icpctools#579]
In the team presentation that shows the university logos on the world map, only show (and drop) each university logo once, even if there are multiple teams from a university.

**Comment by nickygerritsen** [comment]
It actually might have been the first

**Comment by deboer-tim** [comment]
That's what I assumed, until I started 'fixing' the code and noticed that the first is showing the team number, display name, and logo. Presumably the contest doesn't have several teams from the same university *and* same id and same name. :) So it wasn't clear if he wanted an option for the first presentation that shows universities instead of teams, or the last one.

**Comment by nickygerritsen** [comment]
So what Fredrik wants is to show the logo only once but then loop over the teams. I.e. keep the logo on screen while showing 3 teams, then place the logo once on the map

**Comment by nickygerritsen** [comment]
Hey I did this!l today! It’s a flag so you can have both modes
