### ISSUE TITLE
Countdown: status go and 0:

### ISSUE THREAD

**Issue by deboer-tim** [icpctools/icpctools#749]
The countdown presentation has a "Status: Go" that's a but confusing since it means "the contest isn't paused" and isn't related to any of the red items above.

When the countdown is under an hour the clock still has "0:" at the start, originally to keep the 'digital clock' from moving, but maybe it should be removed.

**Comment by clevengr** [comment]
As far as "Status: Go" goes, perhaps have three status values:  "Go" (every button above is green AND the countdown is not paused); "Waiting" or "Blocked"  (the countdown is not paused but one or more buttons is red), and "Paused" (the countdown has been stopped)?   Just an idea/concept...

**Comment by nickygerritsen** [comment]
That could also work yeah

**Comment by MarcoUCM** [comment]
IMHO

- In some scenarios the contest may start even if not all the switches are green because some of them may be just informative (for example YouTube streaming), so I'd prefer to replace "Status: Go" for "Status: active countdown" or something similar. Or even removing the status string when the countdown is not paused or blocked.
- Regarding the "0:" and its removal that could be a problem in some resolutions with the switches because as the number of chars decreases the height of the font increase and some switches may overlap. In fact that's already true in FullHD when hours goes from 10: to 9:
![Captura de pantalla de 2023-04-12 02-03-17](https://user-images.githubusercontent.com/14042085/231315338-9a0675f2-da52-45a5-8e7c-435d604c8ecd.png)
![Captura de pantalla de 2023-04-12 02-06-02](https://user-images.githubusercontent.com/14042085/231315350-9789e045-885b-4c53-a01c-02ca5eb688f6.png)

**Comment by deboer-tim** [comment]
Fix via PR #781.
