### ISSUE TITLE
Balloon printer features for dress rehearsal

### ISSUE THREAD

**Issue by nickygerritsen** [icpctools/icpctools#996]
* Add an option/flag to say 'don't hand out the same balloon color more than once'. So if two problems have the color 'red', and a team solves both, only print out one red balloon page.
* Add an option/flag to say 'don't hand out more than x balloon', so if a team solves 5 problems but the setting is to 3, don't print the last 2.

Should they appear in the table or also be omitted there?

**Comment by clevengr** [comment]
> The first is already supported: if problems have the same uuid property they are 'the same problem' and the second solution won't be awarded a balloon.
> 

I'm not sure that this the same thing as what's being requested (although you could prove me wrong).  The overall point is to make the DR operate "the same, from the Runner's point of view" as the Real Contest.  In the DR, we have "duplicated problems" -- but they are given different LETTERS and they are treated as "different problems" from the contestant's point of view.  Wouldn't such problems have _different_ uuids?

> Do we really need both options (and if so, what contest property and will we use it as often as the first one? :) )
> 
> Today these won't show up in the table since it is a table of balloons awarded (the same way that solving a problem during freeze makes a balloon show up if you have less than 3 solved but not more...). On one hand I can see people getting confused why something isn't in the table... but I could see them being just as confused if we show an entry and don't auto-print or it's not _really_ obvious why.

Again, the objective is to make it so that, from the Runner's POV, the DR works the same as the Real Contest.  If they get a printout, it means they should take a balloon for that printout (because that's what happens in the RC).  So the idea is to make it so that the "summary" at the top during the DR matches what we want the Runners to see/deliver, and that we don't send any printouts for a situation where the Runners shouldn't be delivering a balloon.

**Comment by clevengr** [comment]
And just a followup:  this discussion is just starting; it's _not_ a request to implement it for Astana (unless that happens to be easy to do).  It's more that we want to identify the exact, detailed requirements so that we can work on getting it implemented for WF 2025 (which realistically means having it working for Fall 2024/Spring 2025 Regionals and Championships...)

**Comment by nickygerritsen** [comment]
> > The first is already supported: if problems have the same uuid property they are 'the same problem' and the second solution won't be awarded a balloon.
> 
> I'm not sure that this the same thing as what's being requested (although you could prove me wrong). The overall point is to make the DR operate "the same, from the Runner's point of view" as the Real Contest. In the DR, we have "duplicated problems" -- but they are given different LETTERS and they are treated as "different problems" from the contestant's point of view. Wouldn't such problems have _different_ uuids?

No one sees the UUID, except the code. Since the problem *contents* are the same, they could (should?) have the same UUID, even if the letter (which is contest specific, not problem specific) differs. So I'd say, using the UUID for this would work.

> 
> > Do we really need both options (and if so, what contest property and will we use it as often as the first one? :) )
> > Today these won't show up in the table since it is a table of balloons awarded (the same way that solving a problem during freeze makes a balloon show up if you have less than 3 solved but not more...). On one hand I can see people getting confused why something isn't in the table... but I could see them being just as confused if we show an entry and don't auto-print or it's not _really_ obvious why.
> 
> Again, the objective is to make it so that, from the Runner's POV, the DR works the same as the Real Contest. If they get a printout, it means they should take a balloon for that printout (because that's what happens in the RC). So the idea is to make it so that the "summary" at the top during the DR matches what we want the Runners to see/deliver, and that we don't send any printouts for a situation where the Runners shouldn't be delivering a balloon.

So the current behavior is what we want, right? Don't show any balloons in the summary that aren't actually handed out.

**Comment by clevengr** [comment]
> > > The first is already supported: if problems have the same uuid property they are 'the same problem' and the second solution won't be awarded a balloon.
> > 
> > 
> > I'm not sure that this the same thing as what's being requested (although you could prove me wrong). The overall point is to make the DR operate "the same, from the Runner's point of view" as the Real Contest. In the DR, we have "duplicated problems" -- but they are given different LETTERS and they are treated as "different problems" from the contestant's point of view. Wouldn't such problems have _different_ uuids?
> 
> No one sees the UUID, except the code. Since the problem _contents_ are the same, they could (should?) have the same UUID, even if the letter (which is contest specific, not problem specific) differs. So I'd say, using the UUID for this would work.
> 

Well, there's no guarantee that _all_ "problem content" would be the same (i.e., _identical_).  The titles could be (usually are, IIRC) slightly different; the judges might also slightly tweak other information.  My point was that the "duplicate" problems, while perhaps technically having the same input and output specifications, are essentially "different problems".  As different problems, I would asume they would have separate UUIDs -- and therefore they wouldn't be the "same problem" for purposes of detecting duplicate balloon issuances.  But perhaps we're just saying the same thing in different ways...

> > > Do we really need both options (and if so, what contest property and will we use it as often as the first one? :) )
> > > Today these won't show up in the table since it is a table of balloons awarded (the same way that solving a problem during freeze makes a balloon show up if you have less than 3 solved but not more...). On one hand I can see people getting confused why something isn't in the table... but I could see them being just as confused if we show an entry and don't auto-print or it's not _really_ obvious why.
> > 
> > 
> > Again, the objective is to make it so that, from the Runner's POV, the DR works the same as the Real Contest. If they get a printout, it means they should take a balloon for that printout (because that's what happens in the RC). So the idea is to make it so that the "summary" at the top during the DR matches what we want the Runners to see/deliver, and that we don't send any printouts for a situation where the Runners shouldn't be delivering a balloon.
> 
> So the current behavior is what we want, right? Don't show any balloons in the summary that aren't actually handed out.

Well, from that point of view, yes:  we want the "table of balloons issued" to match the "actual balloons issued" -- i.e. "don't show any balloons in the summary that haven't actually been handed out." 

Said another way, we want (1) set a limit on the total number of balloons handed out; (2) don't send a printout if a balloon isn't supposed to be handed out;  (3) ensure that no more than one balloon of a given color is handed out (because in DR the same color might/could/probably-would be used for multiple problems, even though this never happens in the RC).

**Comment by deboer-tim** [comment]
> > > > The first is already supported: if problems have the same uuid property they are 'the same problem' and the second solution won't be awarded a balloon.
> > > 
> > > 
> > > I'm not sure that this the same thing as what's being requested (although you could prove me wrong). The overall point is to make the DR operate "the same, from the Runner's point of view" as the Real Contest. In the DR, we have "duplicated problems" -- but they are given different LETTERS and they are treated as "different problems" from the contestant's point of view. Wouldn't such problems have _different_ uuids?
> > 
> > 
> > No one sees the UUID, except the code. Since the problem _contents_ are the same, they could (should?) have the same UUID, even if the letter (which is contest specific, not problem specific) differs. So I'd say, using the UUID for this would work.
> 
> Well, there's no guarantee that _all_ "problem content" would be the same (i.e., _identical_). The titles could be (usually are, IIRC) slightly different; the judges might also slightly tweak other information. My point was that the "duplicate" problems, while perhaps technically having the same input and output specifications, are essentially "different problems". As different problems, I would asume they would have separate UUIDs -- and therefore they wouldn't be the "same problem" for purposes of detecting duplicate balloon issuances. But perhaps we're just saying the same thing in different ways...

Yes, understood. But we have a working mechanism for saying when two problems 'are the same' that has been working for years. If you think it should be represented differently in the API, that's fine but should be a discussion in the CLICS/spec repo, not here.

> > > > Do we really need both options (and if so, what contest property and will we use it as often as the first one? :) )
> > > > Today these won't show up in the table since it is a table of balloons awarded (the same way that solving a problem during freeze makes a balloon show up if you have less than 3 solved but not more...). On one hand I can see people getting confused why something isn't in the table... but I could see them being just as confused if we show an entry and don't auto-print or it's not _really_ obvious why.
> > > 
> > > 
> > > Again, the objective is to make it so that, from the Runner's POV, the DR works the same as the Real Contest. If they get a printout, it means they should take a balloon for that printout (because that's what happens in the RC). So the idea is to make it so that the "summary" at the top during the DR matches what we want the Runners to see/deliver, and that we don't send any printouts for a situation where the Runners shouldn't be delivering a balloon.
> > 
> > 
> > So the current behavior is what we want, right? Don't show any balloons in the summary that aren't actually handed out.
> 
> Well, from that point of view, yes: we want the "table of balloons issued" to match the "actual balloons issued" -- i.e. "don't show any balloons in the summary that haven't actually been handed out."
> 
> Said another way, we want (1) set a limit on the total number of balloons handed out; (2) don't send a printout if a balloon isn't supposed to be handed out; (3) ensure that no more than one balloon of a given color is handed out (because in DR the same color might/could/probably-would be used for multiple problems, even though this never happens in the RC).

As per above, (3) is already implemented. And it's semantics, but (2) is implemented because if you solve a second/duplicate problem you don't get awarded a balloon, so it's not in the table and not printed out.

So that leaves (1). Yes, it's totally possible to implement a maxBalloonsPerTeam property. However, given that (3) was requested for years and then we haven't been using it in practice, I'm not really inclined to add another feature without knowing that it is needed for and will be used at a contest.

**Comment by clevengr** [comment]
Ok, this "thread" is getting pretty long; I'm going to suggest that we move the conversation to a better venue.  I'll add it as an agenda item for next Wednesday's SysOps meeting (because I still don't see how it's resolved).

**Comment by deboer-tim** [comment]
Used successfully in Astana. I'm closing the issue since it is 'done', feel free to raise another issue if there's something we want to change about how it is done, or we can discuss on sysops call.
